version: '3'
services:
  app:
    container_name: mic-with-me
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    # command: sh -c "/bin/ash"
    tty: true
    ports:
      - '3030:3030'
